Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -28,6 +28,18 @@ jobs:
       - name: Terraform Init
         run: terraform init
 
+      - name: Check if RDS Cluster Exists
+        id: check_rds
+        run: |
+          cluster_status=$(aws rds describe-db-clusters --db-cluster-identifier galega-aurora --query 'DBClusters[0].Status' --output text || echo "not found")
+          if [ "$cluster_status" != "not found" ]; then
+            echo "RDS Cluster exists."
+            echo "RDS_EXISTS=true" >> $GITHUB_ENV
+          else
+            echo "RDS Cluster does not exist."
+            echo "RDS_EXISTS=false" >> $GITHUB_ENV
+          fi
+
       - name: Terraform Plan
         env:
           TF_LOG: DEBUG
@@ -36,6 +48,7 @@ jobs:
         run: terraform plan
 
       - name: Terraform Apply
+        if: env.RDS_EXISTS == 'false'
         env:
           TF_VAR_db_master_username: ${{ secrets.DB_MASTER_USERNAME }}
           TF_VAR_db_master_password: ${{ secrets.DB_MASTER_PASSWORD }}
