Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -59,16 +59,15 @@ jobs:
           TF_VAR_db_master_password: ${{ secrets.DB_MASTER_PASSWORD }}
         run: terraform apply -auto-approve
 
+      - name: Delay for Resource Propagation
+        run: sleep 30
+
       - name: Terraform Output
         id: terraform_output
         run: |
-          OUTPUT=$(terraform output -raw endpoint 2>&1)
-          if [[ "$OUTPUT" == *"Warning:"* || "$OUTPUT" == *"Error:"* || -z "$OUTPUT" ]]; then
-            echo "Error retrieving Terraform output."
-            echo "ENDPOINT=" >> $GITHUB_ENV
-          else
-            echo "ENDPOINT=$OUTPUT" >> $GITHUB_ENV
-          fi
+          OUTPUT=$(terraform output -raw endpoint 2>&1 || echo "Error")
+          echo "Terraform output: $OUTPUT"
+          echo "ENDPOINT=$OUTPUT" >> $GITHUB_ENV
 
       - name: Install PostgreSQL Client
         run: sudo apt-get install -y postgresql-client
